trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - 'README.md'
      - 'docs/*'

pr:
  branches:
    include:
      - main

jobs:
  - job: PrepEnv
    displayName: 'install dependency'
  - job: Build
    displayName: 'Build Job'
    steps:
      - task: Bash@3
        displayName: 'build frontend'
        inputs:
          targetType: 'inline'
          script: |
            ls
            pwd
            cd app/frontend/src
            npm install
            npm run build
      - task: Bash@3
        displayName: 'build backend'
        inputs:
          targetType: 'inline'
          script: |
            cd app/backend
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            python app.py &



          